server:
  port: 8080

spring:
  datasource:
    url: jdbc:sqlite:memo.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect

logging:
  file:
    name: logs/memo.log
